- apps/Products/templates/home.html
I added a new button in the home.html file to show/hide help.
> Help panel inside BlueXolo

- apps/Products/templates/arguments.html
- apps/Products/templates/phases.html
- apps/Products/templates/source-list.html
- apps/Servers/templates/parameters.html
- apps/Servers/templates/server-profiles.html
- apps/Servers/templates/servers-templates.html
- apps/Testings/templates/collections.html
- apps/Testings/templates/keywords.html
- apps/Testings/templates/list-import-script.html
- apps/Testings/templates/testcases.html
- apps/Testings/templates/testsuites.html
- apps/Users/templates/users.html
This changes every add button to a new location more visible
> #198 adjust-add-button.

- README.md
I added YouTube Links and Contact links in the README file.
> #275 Updated README file

- static/js/dragNDrop/translatorToRobot.js
> Add link to download generated robot code

- apps/Products/forms.py
- apps/Products/templates/create-edit-source.html
- apps/Products/views.py
- apps/Users/models.py
- docker/tools/start-bluexolo.sh
- extracts.py
- requirements.txt
> #17 add button import libraries

- docker/sources/secrets.json
- secrets.json.dist
<h2>List of Changes:</h2>
<ul>
<li>Modify dist platform version from 1.3 to 3.1.0</li>
<li>Modify docker secrets platform version from 0.1.0 to 3.1.0</li>
</ul>
> Update version number

- templates/footer-block.html
<h2>List of Changes:<h2/>
<ul>
<li>Link references updated</li>
<li>Link targets are now a blank tab</li>
<li>Unnecessary links have been removed</li>
</ul>
> Update Quick Links

- apps/Testings/views.py
<h2>List of Changes:</h2>
<ul>
<li>Modify open file mode to read</li>
<li>Wrong escape sequences have been corrected</li>
</ul>
> Fix imported scripts text format

- apps/Testings/data_tables_views.py
- apps/Testings/templates/keywords.html
The "keyword" section now shows all the keywords, native and imported.
> #330 listed imported keywords

- docker/Dockerfile
- docker/tools/build-image
The Dockerfile was modified to use the Ubuntu 18.04 image as a base and to avoid problems with newer systems.
> DockerFile Modified to use Ubuntu 18.04 as base image

- apps/Testings/templates/create-testcase.html
- apps/Testings/templates/create-testsuites.html
- apps/Testings/views.py
- static/js/dragNDrop/translatorToRobot.js
* Add extra data to imported scripts (this makes posible to drag and drop elements).
* Add validations to enable the correct creation of test suites and test cases with native and imported items.
> #369 Add validations to accept imported items

- apps/Products/forms.py
- docker/tools/start-bluexolo.sh
- A double staggered validation was done where it is checked that the URL comes from the official RobotFramework page and ends with ".html"
- Check that the field is not empty.
> #326 invalid url crashes home page

- apps/Products/templates/home.html
* Change success task execution card color from green to blue-grey (neutral color)
* Change text color in the _VIEW RESULT_ button
* Add _Success_ or _Failure_ status in green or red text depending on the real result of the log created (for testing items)
* Add a script to open the output XML file and execute changes in the DOM depending on the content of that file
> Change successfully executed tasks cards design

- docker/scripts/user-startup-tasks.sh
A new file was created that runs from rc.local. In this new file called user-startup-tasks.sh there is the code that solves the problem of Control Flow Sentences. In this file, it will be possible in the future to include other tasks that need to be executed at the start of the BlueXolo container.
The creation of a new image of BlueXolo is necessary for these changes to be reflected.
> Added Solution to Control FLow Sentences

- apps/Servers/views.py
- apps/apis/views.py
- docker/scripts/config-user-and-robot.sh
- docker/scripts/config-user.sh
- docker/tools/start-bluexolo.sh
- requirements.txt
- tools/check_dirs.sh
**Description:**
- Update from pybot to robot command
- Add robot framework to the requirements (for python environment)
- Use imported scripts as native scripts
- Add script to configure bluexolo user
- Modify _start-bluexolo.sh_ to execute the _config-user.sh_ script
- Change the interpreter in the _check_dirs.sh_
> #344 run robot items

- apps/Products/templates/commands.html
- apps/apis/serializers.py
- Fixed commands manual creation bug.
- Fixed commands update bug.
- Fixed create command button unexpected behavior.
> Fixed Commands Bug

- apps/Testings/views.py
> Fixed variables inside a BX item download

- static/js/dragNDrop/translatorToRobot.js
Added a line with the Title to save the script in the database.
> Fixed Test Cases Title

- INSTALL_FOR_WINDOWS.md
- INSTALL_WITH_DOCKER.md
Update documentation to use BlueXolo in docker environments for both Linux and Windows operative systems.
> Update how to install documentation

- apps/Products/templates/stepper.html
- apps/Testings/templates/create-keyword.html
- apps/Testings/templates/create-testcase.html
- apps/Testings/templates/create-testsuites.html
- apps/Testings/templates/edit-import-script.html
- apps/Testings/templates/edit-keyword.html
- apps/Testings/templates/edit-testcase.html
- apps/Testings/templates/edit-testsuites.html
- docker/tools/.gitattributes
- docker/tools/start-bluexolo.bat
- docker/tools/start-bluexolo.sh
- docker/tools/stop-bluexolo.bat
- docker/tools/stop-bluexolo.sh
- templates/base.html
- templates/registration/login.html
**Description:**
* Modify start and stop BlueXolo scripts to also run the Assistant.
* Add bat scripts for Windows users.
* Get required paths from input to avoid script edition, (but there is an option to define static values for the required paths during BlueXolo startup)
* Hide chatbot button from stepper iframes to avoid button duplication.
_Update:_
* More sleep time before startup config to avoid error during ´´´config-user.sh´´´ execution.
* Add .gitattributes files to set all .sh files the LF end of line sequence.
> LF is required in shell scripts that are going to be executed inside of the running bluexolo docker container.
> #390 chatbot integration

- README.md
- User_Guide.md
**Description:**
- Add the User_Guide.md with information to setup all the requirements in BlueXolo to create and run a test case.
- Add a reference to this guide in the Usage section of the README.
> The reference won't work until the user guide file is on master.
> Create BlueXolo user guide and add a link to it in the README
